#ifndef ACOMPILER_VERSION_H
#define ACOMPILER_VERSION_H

#define ACOMPILER_VERSION_MAJOR 0
#define ACOMPILER_VERSION_MINOR 1
#define ACOMPILER_VERSION_PATCH 0
#define ACOMPILER_VERSION_STRING "0.1.0"

#endif // ACOMPILER_VERSION_H
